# Generated by Django 5.2.8 on 2026-05-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at'], 'verbose_name': 'پست ', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
